ifixit/activities/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new/$', views.new, name='new'),
    url(r'^edit/(?P<activity_id>.+)$', views.edit, name='edit'),
    url(r'^ticket/(?P<activity_id>.+)$', views.ticket, name='ticket')
]

ifixit/ifixit/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from . import views

urlpatterns = [
url(r'^$', views.index, name='index'),
url(r'^users/', include('users.urls')),
url(r'^activities/', include('activities.urls')),
url(r'^clients/', include('clients.urls')),
url(r'^admin/', admin.site.urls),
]

ifixit/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new/$',views.new_user, name='new'),
    url(r'^(?P<user_id>.+)/$', views.edit, name='edit')
]

ifixit/activities/models.py
from django.db 	import models
from django.utils import timezone
from users 	 import models as user_models
from clients import models as client_models

class Activity(models.Model):
#id_activity		=       models.AutoField(primary_key=True)
#Enlazar con un unico cliente
    cliente = models.ForeignKey(client_models.Client, on_delete=models.CASCADE)
#Enlazar con un unico tecnico
    tecnico = models.ForeignKey(user_models.User_info, on_delete=models.CASCADE)
    fecha_diagnostico = models.DateTimeField('fecha de diagnostico')
    comentarios = models.CharField(max_length=300)
    diagnostico = models.CharField(max_length=300)
    equipo = models.CharField(max_length=60)
    marca = models.CharField(max_length=60)
    tipo = models.CharField(max_length=20)
    serie = models.CharField(max_length=30)
    estado_actual = models.IntegerField(default=0)
    imei = models.CharField(max_length=16,default='IMEI')

ifixit/activities/forms.py
from django import forms
import datetime
class date_filter(forms.Form):
    date = forms.DateField(initial=datetime.date.today,
                           widget=forms.TextInput(attrs=
                                {'id':'datepicker'})
                           )
class Acitivity_Form(forms.Form):
    #Almacenar el id del cliente
    cliente         =   forms.IntegerField(label='Cliente')
    #Almacenar el id del tecnico
    tecnico         =   forms.IntegerField(label='Tecnico')
    diagnostic_date =   forms.DateField(label='fecha de diagnostico',initial=datetime.date.today)
    comment         =   forms.CharField(label='Observaciones', max_length=300, widget=forms.Textarea(attrs={'rows': 4, 'cols': 40}))
    diagnostic      =   forms.CharField(label='diagnostico', max_length=300,widget=forms.Textarea(attrs={'rows': 4, 'cols': 40}))
    object          =   forms.CharField(label='Equipo', max_length=100)
    mark            =   forms.CharField(label='Marca', max_length=100)
    type            =   forms.CharField(label='Tipo de equipo', max_length=100)
    serie           =   forms.CharField(label='Numero de serie', max_length=100)
    state           =   forms.IntegerField(label='Estado de la actividad')
    imei            =   forms.CharField(label='IMEI', max_length=20)
    print	    =   forms.BooleanField(required=False,initial=True)

class TicketForm(forms.Form):
    Concepto    = forms.CharField(label='Concepto de pago')
    MetodoPago  = forms.CharField(label='Metodo de pago')
    Total       = forms.FloatField(label='Total')
    Fecha       = forms.DateField(label='Fecha de emición',initial=datetime.date.today)
    #ReciboNumero= forms.CharField(label='Numero de recibo')

ifixit/activities/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.utils import timezone
from global_data.session_ctl import session_ctl
from .forms import date_filter,Acitivity_Form,TicketForm

from .models	import Activity
from clients.models import Client
from users.models import User_info
import datetime

from django.db 	import models

def new(request):
	session = session_ctl(request.session)
	error = None
	if not (session.is_active()):
            return redirect("/")
	nombre = session.getName()
	if request.method == 'POST':	#Comprobar formulario si hay
		if (request.POST.get('salir') == ''):#Se solicito logout
			session.logout()#Cerrar sesion y guardar en session del sistema
			session.save_session(request.session)
			return redirect("/")
		form = Acitivity_Form(request.POST)
		if(form.is_valid()):
			try:
				register = Activity()
				register.cliente 			= 	Client.objects.get( id = form.cleaned_data['cliente'])
				register.tecnico 			= 	User_info.objects.get( id =	form.cleaned_data['tecnico'])
				register.fecha_diagnostico 	= 	form.cleaned_data['diagnostic_date']
				register.comentarios		= 	form.cleaned_data['comment']
				register.diagnostico		=   form.cleaned_data['diagnostic']
				register.equipo				= 	form.cleaned_data['object']
				register.marca				=	form.cleaned_data['mark']
				register.tipo				=	form.cleaned_data['type']
				register.serie				=	form.cleaned_data['serie']
				register.estado_actual		=	form.cleaned_data['state']
				register.imei				=	form.cleaned_data['imei']
				register.id_activity		=	form.cleaned_data['imei'] + str(form.cleaned_data['diagnostic_date'])
				register.save()
				if( form.cleaned_data['print'] == True):
					return redirect("/activities/ticket/"+str(register.id))
				else:
					return redirect("/activities/")
			except:
				error = "Verifica los datos del formulario"
		else:
			error = "Verifica los datos del formulario"
	form = Acitivity_Form()
	clients_ids =	Client.objects.all().order_by('-nombre')
	users_ids   =	User_info.objects.all().order_by('-nombre')
	context = { 'form':form , 'clients':clients_ids , 'users':users_ids,
				'error':error,'nombre':nombre}
	return render(request,'activities/new.html',context)

def ticket(request,activity_id):
	session = session_ctl(request.session)
	if not (session.is_active()):
            return redirect("/")
	activity = None
	try:
		activity = Activity.objects.get(id = activity_id)
	except:
		return redirect("/activities/")

	form = TicketForm({	"Fecha": datetime.date.today(),
				"Concepto":"Servicio de reparacion",
				"MetodoPago":"Efectivo",
				"Total":0.0
				})

	Empresa 	= 	"Refacciones y accesorios DCG"
	Empresa_Dir	=	"C.28 # 206 x 25A y 27. Ticul, Yucatán"
	Empresa_Tel	=	["Tel. 972-1035","Cel. 997-103-4547","Cel. 997-103-4537"]
	ticket_nro  = activity.id   #	"0001 - 00000168"
	ticket_date = activity.fecha_diagnostico.date()
	

	context = {'ticket':False,'Empresa_Dir':Empresa_Dir,'Empresa':Empresa,'Empresa_Tel':Empresa_Tel,
	'ticket_nro':ticket_nro,'ticket_date':ticket_date,'activity':activity,'form':form}

	return render(request,'activities/ticket.html',context)
def edit(request,activity_id):
	session = session_ctl(request.session)
	state_list = ['Revisado','En Reparacion','Listo','Entregado']
	activity_state = None
	error = None
	if not (session.is_active()):
            return redirect("/")
	nombre = session.getName()
	if request.method == 'POST':	#Comprobar formulario si hay
		if (request.POST.get('salir') == ''):#Se solicito logout
			session.logout()#Cerrar sesion y guardar en session del sistema
			session.save_session(request.session)
			return redirect("/")
		if (request.POST.get('print') == ''):#Se solicito logout
			#Guardar algo en la session
			return redirect("/activities/ticket/"+activity_id)
		form = Acitivity_Form(request.POST)
		if(form.is_valid()):
			try:
				register = Activity.objects.get(id = activity_id)
				register.estado_actual		=	form.cleaned_data['state']
				register.comentarios		=   form.cleaned_data['comment']
				register.diagnostico	    =   form.cleaned_data['diagnostic']
				register.save()
				return redirect("/activities/")
			except:
				error = "Verifica los datos del formulario"
		else:
			error = "Verifica los datos del formulario"
	try:
		register = Activity.objects.get(id = activity_id)
		#Mostrar los datos en pantalla
		form = Acitivity_Form({
			'cliente':	register.cliente.id,
			'tecnico':	register.tecnico.id,
			'diagnostic_date': register.fecha_diagnostico,
			'comment':	register.comentarios,
			'diagnostic':	register.diagnostico,
			'object':	register.equipo,
			'mark'	:	register.marca,
			'type'	:	register.tipo,
			'serie'	:	register.serie,
			'imei'	:	register.imei,
			'state'	:	register.estado_actual
			})
		activity_state = state_list[ register.estado_actual ]
	except:
		return redirect("/activities/")
	clients_ids =	Client.objects.all().order_by('-nombre')
	users_ids   =	User_info.objects.all().order_by('-nombre')
	context = { 'form':form , 'clients':clients_ids , 'users':users_ids,
				'error':error,'activity_state':activity_state,'nombre':nombre}
	return render(request,'activities/edit.html',context)
	#HttpResponse('Aqui se editan las actividades <a href=\"/activities/ticket/'+ activity_id +'\"> Ticket </a> ')

def index(request):
	session = session_ctl(request.session)
	activity_list   = {'0':'Revisado','1':'En Reparacion','2':'Listo','3':'Entregado'}
	nombre = None
	n_activities = 0
	activities = None
	form = None
	context = None
	msj_0 = "Actividades"
	if not (session.is_active()):
            return redirect("/")
	if request.method == 'POST':	#Comprobar formulario si hay
		if (request.POST.get('salir') == ''):#Se solicito logout
			session.logout()#Cerrar sesion y guardar en session del sistema
			session.save_session(request.session)
			return redirect("/")
		form = date_filter(request.POST)
		if(form.is_valid()):
			#RECUPERAR DATOS DEL FORMULARIO
			dat = form.cleaned_data['date']
			activities 	 = Activity.objects.filter(fecha_diagnostico__gte=
				datetime.date(dat.year,dat.month,dat.day))[:100]
			n_activities = len(activities)
			msj_0 += " para %d/%d/%d"%(dat.day,dat.month,dat.year)
		else:
			n_activities = Activity.objects.count()
			activities = Activity.objects.all()[:100]
	else:
		form = date_filter()
		n_activities = Activity.objects.count()
		activities = Activity.objects.all().order_by('estado_actual')[:100]
	nombre = session.getName()
	context = {'nombre':nombre,'activities':activities,
		'form':form,'n_activities':n_activities,'msj_0':msj_0,'activity_list':activity_list}
	return render(request,'activities/index.html',context)

ifixit/activities/templates/activities/edit.html
<!DOCTYPE html>
<html>
<head>
	<link rel="icon" href="/assets/img/favicon.jpg" type="image/x-icon"/>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="Dashboard">
	<meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">

	<!-- Bootstrap core CSS -->
	<link href="/assets/css/bootstrap.css" rel="stylesheet">
	<!--external css-->
	<link href="/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />

	<!-- Custom styles for this template -->
	<link href="/assets/css/style.css" rel="stylesheet">
	<link href="/assets/css/style-responsive.css" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="/assets/css/zabuto_calendar.css">
	<link rel="stylesheet" type="text/css" href="/assets/js/gritter/css/jquery-ui.css" />
	<link rel="stylesheet" type="text/css" href="/assets/js/gritter/css/jquery.gritter.css" />
	<link rel="stylesheet" type="text/css" href="/assets/lineicons/style.css">
	<script src="/assets/js/jquery.nicescroll.js" type="text/javascript"></script>

	<script src="/assets/js/chart-master/Chart.js"></script>

	<!-- js placed at the end of the document so the pages load faster -->
	<script src="/assets/js/jquery.js"></script>
	<script src="/assets/js/bootstrap.min.js"></script>

</head>
<header>

</header>
<body>
<title>Bienvenido</title>
	<section id="container" >
		<!-- **********************************************************************************************************************************************************
		TOP BAR CONTENT & NOTIFICATIONS
		*********************************************************************************************************************************************************** -->
		<!--header start-->
		<header class="header black-bg">
						<div class="sidebar-toggle-box">
								<div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
						</div>
					<!--logo start-->
					<a href="/#" class="logo"><b>{{nombre}}</b></a>
					<!--logo end-->
					<div class="nav notify-row" id="top_menu">
					</div>
					<form  method="POST" action="{{action_link}}">
					<div class="top-menu">
						<ul class="nav pull-right top-menu">
									{% csrf_token %}
									<li><button name="salir" vaue="salir" class="logout" type="sumbit">Salir</button></li>
						</ul>
					</div>
					<form>
			</header>
		<!--header end-->

		<!-- **********************************************************************************************************************************************************
		MAIN SIDEBAR MENU
		*********************************************************************************************************************************************************** -->
		<!--sidebar start-->
		<aside>
				<div id="sidebar"  class="nav-collapse ">
						<!-- sidebar menu start-->
						<ul class="sidebar-menu" id="nav-accordion">

								<p class="centered"><a href="/"><img src="/assets/img/friends/fr-11.jpg" class="img-circle" width="60"></a></p>
								<h5 class="centered">{{nombre}}</h5>

								<li class="mt">
										<a href="/">
												<i class="fa fa-dashboard"></i>
												<span>Principal</span>
										</a>
								</li>

								<li class="sub-menu">
										<a class="active" href="/activities/" >
												<i class="fa fa-cogs"></i>
												<span>Reparaciones</span>
										</a>
								</li>

								<li class="sub-menu">
										<a href="/users/" >
												<i class="fa fa-book"></i>
												<span>Usuarios</span>
										</a>
								</li>

								<li class="sub-menu">
										<a href="/clients/" >
												<i class="fa fa-book"></i>
												<span>Clientes</span>
										</a>
								</li>
						</ul>
						<!-- sidebar menu end-->
				</div>
		</aside>
		<!--sidebar end-->

		<!-- **********************************************************************************************************************************************************
		MAIN CONTENT
		*********************************************************************************************************************************************************** -->
		<!--main content start-->
		<section id="main-content">
				<section class="wrapper">
						<div class="container">
								<div class="col-lg-10 main-chart">
									<a href="/activities/new">
										<div class="col-md-4 col-sm-2 col-md-offset-1 box0">
											<div class="box1">
								<span class="li_stack"></span>
								<h3>{{n_activities}}</h3>
											</div>
								<p>Registrar Nueva Actividad</p>
										</div>
									</a>
									</div><!-- /row mt -->
					</div><!-- /col-lg-9 END SECTION MIDDLE -->
	<!-- **********************************************************************************************************************************************************
      RIGHT SIDEBAR CONTENT
      *********************************************************************************************************************************************************** -->
							<br><br>
				</section>

				<div class="container">
					<form action="{{link}}" method="post">
						{% csrf_token %}
						{{ form.non_field_errors }}
						<div class="fieldWrapper">
							<h3> Ficha técnica </h>
							<h5> En esta ficha solo se puede modificar el estado del servicio, los comentarios y el diagnostico</h5>
							<br><br>
							<h4> Estado actual del servicio : {{activity_state}} </h4>
							<br><br>
							{{ form.state.errors }}
							<label for="{{ form.subject.id_for_label }}">Actualizar Estado :</label>
							<select name="state" id="id_state">
									<option value="0">Revisado</option>
									<option value="1">En reparacion</option>
									<option value="2">Listo</option>
									<option value="3">Entregado</option>
							</select>
							<br>
							<br>
							{{ form.cliente.errors }}
							<label for="{{ form.subject.id_for_label }}">Cliente :</label>
							{{ form.cliente }}
  							<br>
							{{ form.tecnico.errors }}
							<label for="{{ form.subject.id_for_label }}">Tecnico :</label>
							{{ form.tecnico }}
							<br>
							{{ form.diagnostic_date.errors }}
							<label for="{{ form.subject.id_for_label }}">Fecha de diagnostico :</label>
							{{ form.diagnostic_date }}
							<br>
							{{ form.object.errors }}
							<label for="{{ form.subject.id_for_label }}">Equipo :</label>
							{{ form.object }}
							{{ form.mark.errors }}
							<label for="{{ form.subject.id_for_label }}">Marca :</label>
							{{ form.mark }}
							<br>
							{{ form.type.errors }}
							<label for="{{ form.subject.id_for_label }}">Tipo :</label>
							{{ form.type }}
							{{ form.serie.errors }}
							<label for="{{ form.subject.id_for_label }}">Serie :</label>
							{{ form.serie }}
							<br>
							{{ form.imei.errors }}
							<label for="{{ form.subject.id_for_label }}">IMEI :</label>
							{{ form.imei }}
							<br>
							{{ form.diagnostic.errors }}
							<label for="{{ form.subject.id_for_label }}">Diagnostico :</label>
							{{ form.diagnostic }}
							<br>
							{{ form.comment.errors }}
							<label for="{{ form.subject.id_for_label }}">Observaciones :</label>
							{{ form.comment }}
							<br>
						</div>
						<input type="submit" class="btn btn-primary" value="Guardar"/>

								<a href="/activities/">
									<button type="cancel" name="cancel" class="btn btn-warning">Cancelar</button>
								</a>

						{% if error %}
							<div class="alert alert-warning">
								<strong>Advertencia!</strong> {{error}}
							</div>
						{%endif%}
					</form>
					<form  method="POST" onsubmit="return confirm('¿ Los datos en el formularo son correctos ?');">
						{% csrf_token %}
						<button type="sumbit" name="print" class="btn btn-info">Generar Recibo</button>
					</form>
				</div>
				<br><br>
				<br>
		</section>

	<!-- js placed at the end of the document so the pages load faster -->
	<script src="/assets/js/jquery.js"></script>
	<script src="/assets/js/jquery-1.8.3.min.js"></script>
	<script src="/assets/js/bootstrap.min.js"></script>
	<script class="include" type="text/javascript" src="/assets/js/jquery.dcjqaccordion.2.7.js"></script>
	<script src="/assets/js/jquery.scrollTo.min.js"></script>
	<script src="/assets/js/jquery.nicescroll.js" type="text/javascript"></script>
	<script src="/assets/js/jquery.sparkline.js"></script>


	<!--common script for all pages-->
	<script src="/assets/js/common-scripts.js"></script>
  <script src="/assets/js/jquery-ui.js"></script>
	<script type="text/javascript" src="/assets/js/gritter/js/jquery.gritter.js"></script>
	<script type="text/javascript" src="/assets/js/gritter-conf.js"></script>

	<!--script for this page-->
	<script src="/assets/js/sparkline-chart.js"></script>
	<script src="/assets/js/zabuto_calendar.js"></script>
	<script src="/assets/js/notification.js" type="text/javascript"></script>

	<script type="application/javascript">
        function myNavFunction(id) {
            $("#date-popover").hide();
            var nav = $("#" + id).data("navigation");
            var to = $("#" + id).data("to");
            console.log('nav ' + nav + ' to: ' + to.month + '/' + to.year);
        }
			  $( function() {
			    $("#datepicker").datepicker();
			  } );
  </script>
</body>
</html>

ifixit/activities/templates/activities/new.html
<!DOCTYPE html>
<html>
<head>
	<link rel="icon" href="/assets/img/favicon.jpg" type="image/x-icon"/>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="Dashboard">
	<meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">

	<!-- Bootstrap core CSS -->
	<link href="/assets/css/bootstrap.css" rel="stylesheet">
	<!--external css-->
	<link href="/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />

	<!-- Custom styles for this template -->
	<link href="/assets/css/style.css" rel="stylesheet">
	<link href="/assets/css/style-responsive.css" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="/assets/css/zabuto_calendar.css">
	<link rel="stylesheet" type="text/css" href="/assets/js/gritter/css/jquery-ui.css" />
	<link rel="stylesheet" type="text/css" href="/assets/js/gritter/css/jquery.gritter.css" />
	<link rel="stylesheet" type="text/css" href="/assets/lineicons/style.css">
	<script src="/assets/js/jquery.nicescroll.js" type="text/javascript"></script>

	<script src="/assets/js/chart-master/Chart.js"></script>

	<!-- js placed at the end of the document so the pages load faster -->
	<script src="/assets/js/jquery.js"></script>
	<script src="/assets/js/bootstrap.min.js"></script>

</head>
<header>

</header>
<body>
<title>Bienvenido</title>
	<section id="container" >
		<!-- **********************************************************************************************************************************************************
		TOP BAR CONTENT & NOTIFICATIONS
		*********************************************************************************************************************************************************** -->
		<!--header start-->
		<header class="header black-bg">
						<div class="sidebar-toggle-box">
								<div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
						</div>
					<!--logo start-->
					<a href="/#" class="logo"><b>{{nombre}}</b></a>
					<!--logo end-->
					<div class="nav notify-row" id="top_menu">
					</div>
					<form  method="POST" action="{{action_link}}">
					<div class="top-menu">
						<ul class="nav pull-right top-menu">
									{% csrf_token %}
									<li><button name="salir" vaue="salir" class="logout" type="sumbit">Salir</button></li>
						</ul>
					</div>
					<form>
			</header>
		<!--header end-->

		<!-- **********************************************************************************************************************************************************
		MAIN SIDEBAR MENU
		*********************************************************************************************************************************************************** -->
		<!--sidebar start-->
		<aside>
				<div id="sidebar"  class="nav-collapse ">
						<!-- sidebar menu start-->
						<ul class="sidebar-menu" id="nav-accordion">

								<p class="centered"><a href="/"><img src="/assets/img/friends/fr-11.jpg" class="img-circle" width="60"></a></p>
								<h5 class="centered">{{nombre}}</h5>

								<li class="mt">
										<a href="/">
												<i class="fa fa-dashboard"></i>
												<span>Principal</span>
										</a>
								</li>

								<li class="sub-menu">
										<a class="active" href="/activities/" >
												<i class="fa fa-cogs"></i>
												<span>Reparaciones</span>
										</a>
								</li>
								<li class="sub-menu">
										<a href="/users/" >
												<i class="fa fa-book"></i>
												<span>Usuarios</span>
										</a>
								</li>
								<li class="sub-menu">
										<a href="/clients/" >
												<i class="fa fa-book"></i>
												<span>Clientes</span>
										</a>
								</li>
						</ul>
						<!-- sidebar menu end-->
				</div>
		</aside>
		<!--sidebar end-->

		<!-- **********************************************************************************************************************************************************
		MAIN CONTENT
		*********************************************************************************************************************************************************** -->
		<!--main content start-->
		<section id="main-content">
				<section class="wrapper">
						<div class="container">
								<div class="col-lg-10 main-chart">
									<a href="/activities/new">
										<div class="col-md-4 col-sm-2 col-md-offset-1 box0">
											<div class="box1">
											<span class="li_stack"></span>
											<h3>{{n_activities}}</h3>
											</div>
											<p></p>
										</div>
									</a>
									</div><!-- /row mt -->
					</div><!-- /col-lg-9 END SECTION MIDDLE -->
				<div class="container">
					<h2>{{msj_0}}</h2>
					<div class="list-group">
						{%for activity in activities%}
						<a href="/activities/edit/{{ activity.id_activity }}" class="list-group-item">
      			<h4 class="list-group-item-heading">{{ activity.fecha_diagnostico }}</h4>
      			<p class="list-group-item-text">{{ activity.tecnico.nombre }}</p>
    				</a>
						{%endfor%}
					</div>
				</div>
	<!-- **********************************************************************************************************************************************************
      RIGHT SIDEBAR CONTENT
      *********************************************************************************************************************************************************** -->
							<br><br>
				</section>



				<div class="container">
					<h2>Registrar Nueva Actividad </h2>
					<form action="{{link}}" method="post">
						{% csrf_token %}
						{{ form.non_field_errors }}
						<div class="fieldWrapper">
							<h3> Ficha técnica </h3>
							{{ form.cliente.errors }}
							<label for="{{ form.subject.id_for_label }}">Cliente :</label>
							<select name="cliente" id="id_cliente">
								{%for client in clients%}
    							<option value="{{client.id}}">{{client.nombre}}</option>
								{% endfor %}
  						</select>
							<br>
							{{ form.tecnico.errors }}
							<label for="{{ form.subject.id_for_label }}">Tecnico :</label>
							<select name="tecnico" id="id_tecnico">
								{%for user in users%}
									<option value="{{user.id}}">{{user.nombre}}</option>
								{% endfor %}
							</select>
							<br>
							{{ form.diagnostic_date.errors }}
							<label for="{{ form.subject.id_for_label }}">Fecha de diagnostico :</label>
							{{ form.diagnostic_date }}
							<br>
							{{ form.object.errors }}
							<label for="{{ form.subject.id_for_label }}">Equipo :</label>
							{{ form.object }}
							{{ form.mark.errors }}
							<label for="{{ form.subject.id_for_label }}">Marca :</label>
							{{ form.mark }}
							<br>
							{{ form.type.errors }}
							<label for="{{ form.subject.id_for_label }}">Tipo :</label>
							{{ form.type }}
							{{ form.serie.errors }}
							<label for="{{ form.subject.id_for_label }}">Serie :</label>
							{{ form.serie }}
							<br>
							{{ form.state.errors }}
							<label for="{{ form.subject.id_for_label }}">Estado :</label>
							<select name="state" id="id_state">
									<option value="0">Revisado</option>
									<option value="1">En reparacion</option>
									<option value="2">Listo</option>
									<option value="3">Entregado</option>
							</select>
							{{ form.imei.errors }}
							<label for="{{ form.subject.id_for_label }}">IMEI :</label>
							{{ form.imei }}
							<br>
							{{ form.diagnostic.errors }}
							<label for="{{ form.subject.id_for_label }}">Diagnostico :</label>
							{{ form.diagnostic }}
							<br>
							{{ form.comment.errors }}
							<label for="{{ form.subject.id_for_label }}">Observaciones :</label>
							{{ form.comment }}
							<br>
							{{ form.print.errors }}
							<label for="{{ form.subject.id_for_label }}">¿Imprimir? :</label>
							{{ form.print }}
							<br>
						</div>
						<input type="submit" class="btn btn-primary" value="Guardar"/>

								<a href="/activities/">
									<button type="cancel" name="cancel" class="btn btn-warning">Cancelar</button>
								</a>

						{% if error %}
							<div class="alert alert-warning">
								<strong>Advertencia!</strong> {{error}}
							</div>
						{%endif%}
					</form>
					{%if edit%}
					<form  method="POST" onsubmit="return confirm('¿Realmente desea eliminar a \'{{form.name.value}}\' ?');">
						{% csrf_token %}
						<button type="sumbit" name="remove" class="btn btn-danger">Remove</button>
					</form>
					{%endif%}
				</div>
				<br><br>
				<br>
		</section>

	<!-- js placed at the end of the document so the pages load faster -->
	<script src="/assets/js/jquery.js"></script>
	<script src="/assets/js/jquery-1.8.3.min.js"></script>
	<script src="/assets/js/bootstrap.min.js"></script>
	<script class="include" type="text/javascript" src="/assets/js/jquery.dcjqaccordion.2.7.js"></script>
	<script src="/assets/js/jquery.scrollTo.min.js"></script>
	<script src="/assets/js/jquery.nicescroll.js" type="text/javascript"></script>
	<script src="/assets/js/jquery.sparkline.js"></script>


	<!--common script for all pages-->
	<script src="/assets/js/common-scripts.js"></script>
  <script src="/assets/js/jquery-ui.js"></script>
	<script type="text/javascript" src="/assets/js/gritter/js/jquery.gritter.js"></script>
	<script type="text/javascript" src="/assets/js/gritter-conf.js"></script>

	<!--script for this page-->
	<script src="/assets/js/sparkline-chart.js"></script>
	<script src="/assets/js/zabuto_calendar.js"></script>
	<script src="/assets/js/notification.js" type="text/javascript"></script>

	<script type="application/javascript">
        function myNavFunction(id) {
            $("#date-popover").hide();
            var nav = $("#" + id).data("navigation");
            var to = $("#" + id).data("to");
            console.log('nav ' + nav + ' to: ' + to.month + '/' + to.year);
        }
			  $( function() {
			    $("#datepicker").datepicker();
			  } );
  </script>
</body>
</html>