ifixit/ifixit/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from . import views

urlpatterns = [
url(r'^$', views.index, name='index'),
url(r'^users/', include('users.urls')),
url(r'^activities/', include('activities.urls')),
url(r'^clients/', include('clients.urls')),
url(r'^admin/', admin.site.urls),
]

ifixit/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new/$',views.new_user, name='new'),
    url(r'^(?P<user_id>.+)/$', views.edit, name='edit')
]

ifixit/users/models.py
from django.db import models

class User_info(models.Model):
	nombre 		= models.CharField(max_length=100)
	user_name   = models.CharField(max_length=30,default='user_name')
	date   		= models.DateTimeField('fecha de nacimiento')
	tel    		= models.CharField(max_length=10)
	mail   		= models.CharField(max_length=100)
	psw       	= models.CharField(max_length=30,default='********')
	job       	= models.IntegerField(default=1)

#{{ form.cliente }}
#{{ form.tecnico }}

ifixit/users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
import datetime

class UserForm(forms.Form):
    name = forms.CharField(label='Tu nombre', max_length=100)
    user_name = forms.CharField(label='Nombre de usuario',max_length=30)
    psw1  = forms.CharField(label='Contraseña',widget=forms.PasswordInput)
    psw2  = forms.CharField(label='Confirma contraseña',widget=forms.PasswordInput)
    mail = forms.EmailField(required=True)
    date = forms.DateField(initial=datetime.date.today)
    phone = forms.CharField(label='Numero telefonico',max_length=10)

ifixit/users/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse,Http404

from django.template import loader
from activities.models import Activity
from .forms  import UserForm
from .models import User_info

from global_data.session_ctl import session_ctl
#Se crean entradas a base de datos


def index(request):
	users = None
	session = session_ctl(request.session)#Creamos un objeto de control de sesion
	new_user_link = '#'
	#Guardar banderas de sesion que no se eliminan hasta que se elimine en ejecucion
	#Esta pagina unicamente carga los datos cuando se solicita
	#en un numero par de veces
	#
	if not session.is_active():
		return redirect("/")
	if request.method == 'POST':	#Comprobar formulario si hay
		if (request.POST.get('salir') == ''):
			session.logout()#Cerrar sesion y guardar en session del sistema
			session.save_session(request.session)
			return redirect("/")
	users = User_info.objects.all()
	n_activities = Activity.objects.count()
	n_users = User_info.objects.count()
	context = {'users':users,'nombre':session.getName(),
	'n_users':n_users,'n_activities':n_activities}
	return render(request,'users/index.html',context)

def edit(request,user_id):
	session = session_ctl(request.session)#Creamos un objeto de control de sesion
	error = None
	success = None
	#Guardar banderas de sesion que no se eliminan hasta que se elimine en ejecucion
	#Esta pagina unicamente carga los datos cuando se solicita
	#en un numero par de veces
	#
	if not session.is_active():
		return redirect("/users")

	if request.method == 'POST':
		form = UserForm(request.POST)

		if form.is_valid():
			if form.cleaned_data['psw1'] == form.cleaned_data['psw2']:
				#Todo ha salido OK!
				answered = True
				success = "Se han guardado los datos correctamente"
				#user = User_info()#Creamos la instancia de base de datos
				user = User_info.objects.get(id=user_id)
				flag = False
				try:
					#Si el nombre de usuario ya existe entonces se comprueba que sea de el mismo
					user_t = User_info.objects.get(user_name= form.cleaned_data['user_name'])
					if(user_t.nombre == user.nombre):
						flag = True
					else:
						error = "El nombre de usuario ya existe para -> "+user_t.nombre
						flag = False
				except:
					flag = True
				if(flag):
					#Asignamos los valores personales
					user.nombre = form.cleaned_data['name']
					user.date   = form.cleaned_data['date']
					user.tel    = form.cleaned_data['phone']
					user.mail   = form.cleaned_data['mail']
					#Asignamos los valores de usuario
					user.user_name = form.cleaned_data['user_name']
					user.psw = form.cleaned_data['psw1']
					user.job = 5 #La jerarquia mas baja
					#Si todo esta correcto se almacena en la base de datos
					user.save()
					return redirect("/users")
			else:
				error = "Las contraseñas no coinciden"
		else:
			#Comprobar formulario si hay para solicitar logout
			if (request.POST.get('salir') == ''):
				session.logout()#Cerrar sesion y guardar en session del sistema
				session.save_session(request.session)
				return redirect("/")
			if(request.POST.get('remove') == ''):
				#Eliminar elemento!
				user = User_info.objects.get(id=user_id)
				user.delete()
				return redirect("/users")
			error = 'Verifique los datos del formulario'
	#Comprobar el nombre la existencia del usuario
	try:
		link = '/users/'+user_id+'/'#Los formularios post deben ser activados con un / al final c:
		answered = False

		user = User_info.objects.get(id=user_id)
		form = UserForm({
			'name' : user.nombre,
			'user_name' : user.user_name,
			'psw1' : user.psw,
			'psw2' : user.psw,
			'mail' : user.mail,
			'date' : user.date,
			'phone': user.tel
		})
		context = {'nombre':session.getName(),'form':form,'link':link,'success':success,'error':error,'edit':True,'error':error}
		return render(request,'users/new_user.html',context)
	except:
		return redirect('/users')

def new_user(request):
	link = '/users/new/'#Los formularios post deben ser activados con un / al final c:
	name = None
	error = None
	success = None
	session = session_ctl(request.session)#Creamos un objeto de control de sesion
	#Guardar banderas de sesion que no se eliminan hasta que se elimine en ejecucion
	#Esta pagina unicamente carga los datos cuando se solicita
	#en un numero par de veces
	#
	if not session.is_active():
		return redirect("/")
#	if(session.getId is not 1):
#		return redirect("/users/")
	if request.method == 'POST':
		form = UserForm(request.POST)
		if form.is_valid():
			try:
				#Evitar que se cree otro usuario con el mismo nombre de usuario
				user_t = User_info.objects.get(user_name= form.cleaned_data['user_name'])
			except:
				if form.cleaned_data['psw1'] == form.cleaned_data['psw2']:
					#Todo ha salido OK!
					answered = True
					success = "Se han guardado los datos correctamente"
					user = User_info()#Creamos la instancia de base de datos
					#Asignamos los valores personales
					user.nombre = form.cleaned_data['name']
					user.date   = form.cleaned_data['date']
					user.tel    = form.cleaned_data['phone']
					user.mail   = form.cleaned_data['mail']
					#Asignamos los valores de usuario
					user.user_name = form.cleaned_data['user_name']
					user.psw = form.cleaned_data['psw1']
					user.job = 5 #La jerarquia mas baja
					#Si todo esta correcto se almacena en la base de datos
					user.save()
					return redirect("/users/")
				else:
					error = 'La contraseña no coincide'
			error = "El nombre de usuario ya existe para -> "+user_t.nombre		
		if request.method == 'POST':	#Comprobar formulario si hay
			if (request.POST.get('salir') == ''):
				session.logout()#Cerrar sesion y guardar en session del sistema
				session.save_session(request.session)
				return redirect("/")
	else:
		form = UserForm()
	context = {'nombre':session.getName(),'form':form,'link':link,'success':success,'error':error}
	return render(request,'users/new_user.html',context)

ifixit/users/templates/users/index.html
<!DOCTYPE html>
<html>
<head>
	<link rel="icon" href="/assets/img/favicon.jpg" type="image/x-icon"/>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="Dashboard">
	<meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">

	<!-- Bootstrap core CSS -->
	<link href="/assets/css/bootstrap.css" rel="stylesheet">
	<!--external css-->
	<link href="/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />

	<!-- Custom styles for this template -->
	<link href="/assets/css/style.css" rel="stylesheet">
	<link href="/assets/css/style-responsive.css" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="/assets/js/gritter/css/jquery.gritter.css" />
	<link rel="stylesheet" type="text/css" href="/assets/lineicons/style.css">

	<!-- js placed at the end of the document so the pages load faster -->
	<script src="/assets/js/jquery.js"></script>
	<script src="/assets/js/bootstrap.min.js"></script>

</head>
<header>

</header>
<body>
	{% if login %}
	<script type="text/javascript" src="assets/js/jquery.backstretch.min.js"></script>
	<script>
			$.backstretch("/assets/img/rubber-rings-2512269.jpg", {speed: 500});
	</script>
<title>Inicio de sesión</title>
<div id="login-page">
	<div class="container">
			<form class="form-login" action="{{ action_link }}" method="POST">
				<h2 class="form-login-heading">sign in now</h2>
				<div class="login-wrap">
						{% csrf_token %}
						{{ login.non_field_errors }}
						<h2 class="form-signin-heading">Por favor, inicie sesión</h2>
						{{ login.user_name.errors }}
						<input name="user_name" maxlength="30" id="id_user_name"type="text" class="form-control" placeholder="{{login.user_name.label}}" autofocus required>
						<br>
						{{ login.psw.errors }}
						<input name="psw" id="id_psw" type="password" class="form-control" placeholder="{{login.psw.label}}" required>
						<label class="checkbox">
						</label>
						<button class="btn btn-theme btn-block" type="submit"><i class="fa fa-lock"></i> SIGN IN</button>
						<hr>
				</div>
			</form>

	</div>
</div>
	{% else %}
<title>Bienvenido</title>
	<section id="container" >
		<!-- **********************************************************************************************************************************************************
		TOP BAR CONTENT & NOTIFICATIONS
		*********************************************************************************************************************************************************** -->
		<!--header start-->
		<header class="header black-bg">
						<div class="sidebar-toggle-box">
								<div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
						</div>
					<!--logo start-->
					<a href="/#" class="logo"><b>{{nombre}}</b></a>
					<!--logo end-->
					<div class="nav notify-row" id="top_menu">
					</div>
					<form  method="POST" action="{{action_link}}">
					<div class="top-menu">
						<ul class="nav pull-right top-menu">
									{% csrf_token %}
									<li><button name="salir" vaue="salir" class="logout" type="sumbit">Salir</button></li>
						</ul>
					</div>
					<form>
			</header>
		<!--header end-->

		<!-- **********************************************************************************************************************************************************
		MAIN SIDEBAR MENU
		*********************************************************************************************************************************************************** -->
		<!--sidebar start-->
		<aside>
				<div id="sidebar"  class="nav-collapse ">
						<!-- sidebar menu start-->
						<ul class="sidebar-menu" id="nav-accordion">

								<p class="centered"><a href="/"><img src="/assets/img/friends/fr-11.jpg" class="img-circle" width="60"></a></p>
								<h5 class="centered">{{nombre}}</h5>

								<li class="mt">
										<a href="/">
												<i class="fa fa-dashboard"></i>
												<span>Principal</span>
										</a>
								</li>

								<li class="sub-menu">
										<a href="/activities/" >
												<i class="fa fa-cogs"></i>
												<span>Reparaciones</span>
										</a>
								</li>
								<li class="sub-menu">
										<a class = "active" href="/users/" >
												<i class="fa fa-book"></i>
												<span>Usuarios</span>
										</a>
								</li>
								<li class="sub-menu">
										<a href="/clients/" >
												<i class="fa fa-book"></i>
												<span>Clientes</span>
										</a>
								</li>
						</ul>
						<!-- sidebar menu end-->
				</div>
		</aside>
		<!--sidebar end-->

		<!-- **********************************************************************************************************************************************************
		MAIN CONTENT
		*********************************************************************************************************************************************************** -->
		<!--main content start-->
		<section id="main-content">
				<section class="wrapper">
					<div class="container">
					<div class="col-lg-10 main-chart">
								<a href="/users/new">
										<div class="col-md-4 col-sm-2 col-md-offset-1 box0">
											<div class="box1">
												<span class="li_news"></span>
												<h3>{{n_users}}</h3>
											</div>
											<p>Registrar Nuevo Usuario</p>
										</div>
								</a>
					</div>
				</div>
</section>
					<div class="container">
						<h2>{{msj_0}}</h2>
						<div class="list-group">
							{%for user in users%}
							<a href="/users/{{ user.id }}" class="list-group-item">
							<h4 class="list-group-item-heading">{{ user.nombre }}</h4>
							<p class="list-group-item-text">{{ user.tel }}</p>
							</a>
							{%endfor%}
						</div>
					</div>

		</section>

	<!-- js placed at the end of the document so the pages load faster -->
	<script src="/assets/js/jquery.js"></script>
	<script src="/assets/js/jquery-1.8.3.min.js"></script>
	<script src="/assets/js/bootstrap.min.js"></script>
	<script class="include" type="text/javascript" src="/assets/js/jquery.dcjqaccordion.2.7.js"></script>

	<!--common script for all pages-->
	<script src="/assets/js/common-scripts.js"></script>

	<script type="text/javascript" src="/assets/js/gritter/js/jquery.gritter.js"></script>
	<script type="text/javascript" src="/assets/js/gritter-conf.js"></script>

	<script src="/assets/js/notification.js" type="text/javascript"></script>
	<script src="/assets/js/CookieCtl.js" type="text/javascript"></script>
	<script type="application/javascript">
		if(getCookie("cookie_life")==""){
			setCookie("cookie_life","true");
			setCookie("notification","done!");
			show_notification("Bienvenido",
					"Hola de nuevo {{nombre}}",//Mensaje
					'assets/img/favicon.jpg',
					true,
					'',
					'my-sticky-class'
			);
		}
	</script>

	<script type="application/javascript">
        function myNavFunction(id) {
            $("#date-popover").hide();
            var nav = $("#" + id).data("navigation");
            var to = $("#" + id).data("to");
            console.log('nav ' + nav + ' to: ' + to.month + '/' + to.year);
        }
    </script>
</body>
{%endif%}
</html>

ifixit/users/templates/users/new_user.html
<!DOCTYPE html>
<html>
<head>
	<link rel="icon" href="/assets/img/favicon.jpg" type="image/x-icon"/>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="Dashboard">
	<meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">

	<!-- Bootstrap core CSS -->
	<link href="/assets/css/bootstrap.css" rel="stylesheet">
	<!--external css-->
	<link href="/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />

	<!-- Custom styles for this template -->
	<link href="/assets/css/style.css" rel="stylesheet">
	<link href="/assets/css/style-responsive.css" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="/assets/js/gritter/css/jquery.gritter.css" />
	<link rel="stylesheet" type="text/css" href="/assets/lineicons/style.css">

	<!-- js placed at the end of the document so the pages load faster -->
	<script src="/assets/js/jquery.js"></script>
	<script src="/assets/js/bootstrap.min.js"></script>

</head>
<header>

</header>
<body>
<title>Bienvenido</title>
	<section id="container" >
		<!-- **********************************************************************************************************************************************************
		TOP BAR CONTENT & NOTIFICATIONS
		*********************************************************************************************************************************************************** -->
		<!--header start-->
		<header class="header black-bg">
						<div class="sidebar-toggle-box">
								<div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
						</div>
					<!--logo start-->
					<a href="/#" class="logo"><b>{{nombre}}</b></a>
					<!--logo end-->
					<div class="nav notify-row" id="top_menu">
					</div>
					<form  method="POST" action="{{action_link}}">
					<div class="top-menu">
						<ul class="nav pull-right top-menu">
									{% csrf_token %}
									<li><button name="salir" vaue="salir" class="logout" type="sumbit">Salir</button></li>
						</ul>
					</div>
					<form>
			</header>
		<!--header end-->

		<!-- **********************************************************************************************************************************************************
		MAIN SIDEBAR MENU
		*********************************************************************************************************************************************************** -->
		<!--sidebar start-->
		<aside>
				<div id="sidebar"  class="nav-collapse ">
						<!-- sidebar menu start-->
						<ul class="sidebar-menu" id="nav-accordion">

								<p class="centered"><a href="/"><img src="/assets/img/friends/fr-11.jpg" class="img-circle" width="60"></a></p>
								<h5 class="centered">{{nombre}}</h5>

								<li class="mt">
										<a href="/">
												<i class="fa fa-dashboard"></i>
												<span>Principal</span>
										</a>
								</li>

								<li class="sub-menu">
										<a href="/activities/" >
												<i class="fa fa-cogs"></i>
												<span>Reparaciones</span>
										</a>
								</li>
								<li class="sub-menu">
										<a class = "active" href="/users/" >
												<i class="fa fa-book"></i>
												<span>Usuarios</span>
										</a>
								</li>
								<li class="sub-menu">
										<a href="/clients/" >
												<i class="fa fa-book"></i>
												<span>Clientes</span>
										</a>
								</li>
						</ul>
						<!-- sidebar menu end-->
				</div>
		</aside>
		<!--sidebar end-->

		<!-- **********************************************************************************************************************************************************
		MAIN CONTENT
		*********************************************************************************************************************************************************** -->
		<!--main content start-->
		<section id="main-content">
				<section class="wrapper">
						<div class="container">
					     <div class="col-lg-9 main-chart">
								      <a href="/users/new">
										     <div class="col-md-4 col-sm-2 col-md-offset-1 box0">
											   <div class="box1">
												  <span class="li_news"></span>
											    <h3>{{n_users}}</h3>
											   </div>
											    <p>Usuarios registrados.</p>
										     </div>
								      </a>
					    </div>
						</div>
          </section>
					<div class="container">
            {%if edit%}
              <h2>Editar Usuario</h2>
            {%else%}
						  <h2>Nuevo Usuario</h2>
            {% endif %}
            <form action="{{link}}" method="post">
              {% csrf_token %}
              {{ form.non_field_errors }}
              <div class="fieldWrapper">
                <h3> Datos de contacto </h3>
                {{ form.name.errors }}
                <label for="{{ form.subject.id_for_label }}">Nombre :</label>
                {{ form.name }}
                <br>
                {{ form.date.errors }}
                <label for="{{ form.subject.id_for_label }}">Fecha de nacimiento :</label>
                {{ form.date }}
                <br>
                {{ form.phone.errors }}
                <label for="{{ form.subject.id_for_label }}">Teléfono :</label>
                {{ form.phone }}
                <h3> Datos de cuenta </h3>
                {{ form.user_name.errors }}
                <label for="{{ form.subject.id_for_label }}">Nombre de usuario :</label>
                {{ form.user_name }}
                <br>
                {{ form.psw1.errors }}
                <label for="{{ form.subject.id_for_label }}">Contraseña :</label>
                {{ form.psw1 }}
                <br>
                {{ form.psw2.errors }}
                <label for="{{ form.subject.id_for_label }}">Confirmar contraseña :</label>
                {{ form.psw2 }}
                <br>
                {{ form.mail.errors }}
                <label for="{{ form.subject.id_for_label }}">E-mail :</label>
                {{ form.mail }}
                <br>
              </div>
              <input type="submit" class="btn btn-primary" value="Guardar"/>
                  <a href="/users/">
                    <button type="cancel" name="cancel" class="btn btn-warning">Cancelar</button>
                  </a>
              {% if error %}
                <div class="alert alert-warning">
                  <strong>Advertencia!</strong> {{error}}
                </div>
              {%endif%}
            </form>
            {%if edit%}
            <form  method="POST" onsubmit="return confirm('¿Realmente desea eliminar a \'{{form.name.value}}\' ?');">
  					  {% csrf_token %}
              <button type="sumbit" name="remove" class="btn btn-danger">Remove</button>
            </form>
            {%endif%}
					</div>
		</section>

	<!-- js placed at the end of the document so the pages load faster -->
	<script src="/assets/js/jquery.js"></script>
	<script src="/assets/js/jquery-1.8.3.min.js"></script>
	<script src="/assets/js/bootstrap.min.js"></script>
	<script class="include" type="text/javascript" src="/assets/js/jquery.dcjqaccordion.2.7.js"></script>

	<!--common script for all pages-->
	<script src="/assets/js/common-scripts.js"></script>

	<script type="text/javascript" src="/assets/js/gritter/js/jquery.gritter.js"></script>
	<script type="text/javascript" src="/assets/js/gritter-conf.js"></script>

	<script src="/assets/js/notification.js" type="text/javascript"></script>
	<script src="/assets/js/CookieCtl.js" type="text/javascript"></script>
	<script type="application/javascript">
		if(getCookie("cookie_life")==""){
			setCookie("cookie_life","true");
			setCookie("notification","done!");
			show_notification("Bienvenido",
					"Hola de nuevo {{nombre}}",//Mensaje
					'assets/img/favicon.jpg',
					true,
					'',
					'my-sticky-class'
			);
		}else{

		}
	</script>

	<script type="application/javascript">
        function myNavFunction(id) {
            $("#date-popover").hide();
            var nav = $("#" + id).data("navigation");
            var to = $("#" + id).data("to");
            console.log('nav ' + nav + ' to: ' + to.month + '/' + to.year);
        }
    </script>
</body>
</html>